image:
  repository: 493042495566.dkr.ecr.us-east-2.amazonaws.com/nimbus-retail/catalog-service
  tag: "21"


secretName: catalog-service-secrets

env:
  - name: PORT
    value: "3000"
  - name: DB_NAME
    value: "catalog"

secretEnv:
  - name: DB_HOST
    key: db-host
  - name: DB_PASSWORD
    key: db-password
