image:
  repository: 493042495566.dkr.ecr.us-east-2.amazonaws.com/nimbus-retail/catalog-service
  tag: "21"


secretName: catalog-service-secrets

env:
  - name: PORT
    value: "3000"

secretEnv:
  - name: DATABASE_URL
    key: database-url
