image:
  repository: 493042495566.dkr.ecr.us-east-2.amazonaws.com/nimbus-retail/catalog-service
  tag: "21"

secretName: catalog-service-secrets

livenessProbe:
  path: /healthz

readinessProbe:
  path: /readyz

env:
  - name: PORT
    value: "3000"
  - name: REDIS_URL
    value: "redis://nimbus-retail-redis.hfccii.ng.0001.use2.cache.amazonaws.com:6379"

secretEnv:
  - name: DATABASE_URL
    key: database-url
