image:
  repository: 493042495566.dkr.ecr.us-east-2.amazonaws.com/nimbus-retail/notification-service
  tag: "20"

secretName: notification-service-secrets

livenessProbe:
  path: /healthz

readinessProbe:
  path: /readyz

env:
  - name: PORT
    value: "3000"
  - name: KAFKA_GROUP_ID
    value: "notification-service"
  - name: KAFKA_BROKERS
    value: "kafka:9092"
