image:
  repository: 493042495566.dkr.ecr.us-east-2.amazonaws.com/nimbus-retail/notification-service
  tag: "20"

secretName: notification-service-secrets

env:
  - name: PORT
    value: "3000"
  - name: KAFKA_GROUP_ID
    value: "notification-service"

secretEnv:
  - name: KAFKA_BROKER
    key: kafka-broker
