image:
  repository: 493042495566.dkr.ecr.us-east-2.amazonaws.com/nimbus-retail/order-service
  tag: "19"

secretName: order-service-secrets

livenessProbe:
  path: /healthz

readinessProbe:
  path: /readyz

env:
  - name: PORT
    value: "3000"
  - name: NODE_TLS_REJECT_UNAUTHORIZED
    value: "0"

secretEnv:
  - name: DATABASE_URL
    key: database-url
  - name: JWT_SECRET
    key: jwt-secret
