apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hansonjohnny/nimbs-platform
    targetRevision: main
    path: helm/nimb-service
    helm:
      valueFiles:
        - ../values/notification-service.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nimb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
