apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: nimb
spec:
  type: ExternalName
  externalName: kafka-kafka-bootstrap.kafka.svc.cluster.local
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
